#source:
#  dbms: oracle
#  uri: jdbc:oracle:thin:@localhost:1521/orclpdb1.localdomain
#  username: test
#  passwd: test
#  owner: ats
#  tablename: t_part_rim, t_part_consensus

source:
  dbms: mysql
  uri: jdbc:mysql://207.180.195.131:3306/ats?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
  username: user
  passwd: password
  dbname: dbname
  tablename: table1,table2,table3
  
target:
  dbms: MongoDB
  uri: mongodb://user:password@localhost:30000,localhost:30001,localhost:30002/test?replicaSet=rs0
  dbname: test

---
logging:
  level:
    root: error
    sun.rmi: error
    org.mongodb: info
    org.springframework: info
    com.mongodb.autotemplate: debug
    com.zaxxer.hikari: off
