#source:
#  dbms: oracle
#  uri: jdbc:oracle:thin:@localhost:1521/orclpdb1.localdomain
#  username: test
#  passwd: test
#  owner: ats
#  tablename: t_part_rim, t_part_consensus

source:
  dbms: mysql
  uri: jdbc:mysql://127.0.0.1:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
  username: test
  passwd: test
  dbname: test
  tablename: table1, table2, table3, table4

target:
  dbms: MongoDB
  uri: mongodb://user:password@localhost:30000,localhost:30001,localhost:30002/test?authSource=admin&replicaSet=myRS
  dbname: test

---
logging:
  level:
    root: error
    sun.rmi: error
    org.mongodb: info
    org.springframework: info
    com.mongodb.autotemplate: debug
    com.zaxxer.hikari: off
